Rentbw modeling systemv
systemv/eosio.contracts pull request #4
Opened 2020-09-18 17:50 UTC by deckb

## Change Description

Use ISO compliant timestamp strings for input and config

## Deployment Changes
- [ ] Deployment Changes

## API Changes
- [ ] API Changes

## Documentation Additions
- [ ] Documentation Additions

2020-09-18 17:54 UTC, Max-B1 commented on .vscode/settings.json
> +{
Does the project need this file?

2020-09-18 17:56 UTC, Max-B1 commented on _model_config.json
> +        "target_timestamp": "2022-01-01T00:00:00.000",
There is no timezone in the timestamp

2020-09-18 17:57 UTC, Max-B1 commented on _rentbw_input.csv
> +2021-01-01T19:00:00,configrentbw,test.json,0,0,0,0,0,0
There is no timezone in the timestamp

2020-09-18 18:02 UTC, Max-B1 requested changes
There is no timezone in timestamps. I suggest to use ISO-8601 and provide all timestamps in UTC. Example: 2020-09-18T07:58:07.000Z

2020-09-18 18:02 UTC, deckb commented on .vscode/settings.json
> +{
It does not. I removed it and added to .gitignore

2020-09-18 18:39 UTC, deckb commented on _model_config.json
> +        "target_timestamp": "2022-01-01T00:00:00.000",
I attempted to add the "Z" to the end and got the message "unable to convert ISO-formatted string to fc::time_point_sec" from 
https://github.com/EOSIO/eos/blob/0d87dff8bee56179aa01472dd00a089b2aa7b9fa/libraries/fc/src/time.cpp#L44

2020-09-18 18:39 UTC, deckb commented on _rentbw_input.csv
> +2021-01-01T19:00:00,configrentbw,test.json,0,0,0,0,0,0
same as above.

2020-09-25 14:06 UTC, Max-B1 approved these changes
I confirm that fc::time_point can't parse time zones when converting strings to time_point.
I'll work on parsing time zones later.

2020-09-28 14:19 UTC, merged